### ISSUE TITLE
session clear !!

### ISSUE THREAD

**Issue by aa-hridoy** [dgvai/laravel-sslcommerz#1]
vaiya payment jokhon success ba cancel kora hoy tokhon session theke sob data clean hoiye jay !! ki kora jay vaiya ??

**Comment by dgvai** [comment]
bhaiya, ei package ti to session niye kaj kore na, apni apnar  application e session e data dhore rakhle sheta dhore thakbe, ei package ti ``SSLCommerz::class`` er ekti instance create kore sudhu, jeta re-initializable.
