### ISSUE TITLE
Need to  update guzzlehttp/guzzle  version

### ISSUE THREAD

**Issue by mdsohelmia** [dgvai/laravel-sslcommerz#2]
Problem 1
    - dgvai/laravel-sslcommerz[1.0.0, ..., 1.0.3] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires dgvai/laravel-sslcommerz ^1.0 -> satisfiable by dgvai/laravel-sslcommerz[1.0.0, 1.0.1, 1.0.2, 1.0.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by sharafat** [comment]
@sohel1999 fixed in version 1.0.4.
